export const allClothes = [
    {
        clothes_aid: 1,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "399",
        clothes_image: "na-card-a1.jpg",
        clothes_category: "Summer",
        clothes_is_active: true,
    },
    {
        clothes_aid: 2,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "231",
        clothes_image: "na-card-b1.jpg",
        clothes_category: "Summer",
        clothes_is_active: false,
    },
    {
        clothes_aid: 3,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "989",
        clothes_image: "na-card-c1.jpg",
        clothes_category: "Summer",
        clothes_is_active: true,
    },
    {
        clothes_aid: 4,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "342",
        clothes_image: "na-card-d1.jpg",
        clothes_category: "Summer",
        clothes_is_active: false,
    },
    {
        clothes_aid: 5,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "199",
        clothes_image: "na-card-e1.jpg",
        clothes_category: "Summer",
        clothes_is_active: true,
    },
    {
        clothes_aid: 6,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "379",
        clothes_image: "na-card-f1.jpg",
        clothes_category: "Summer",
        clothes_is_active: true,
    },
    {
        clothes_aid: 7,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "349",
        clothes_image: "na-card-g1.jpg",
        clothes_category: "Summer",
        clothes_is_active: false,
    },
    {
        clothes_aid: 8,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "699",
        clothes_image: "na-card-h1.jpg",
        clothes_category: "Summer",
        clothes_is_active: true,
    },
    {
        clothes_aid: 9,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "299",
        clothes_image: "na-card-i1.jpg",
        clothes_category: "Summer",
        clothes_is_active: true,
    },
    {
        clothes_aid: 10,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "3955",
        clothes_image: "na-card-j1.jpg",
        clothes_category: "Summer",
        clothes_is_active: true,
    },
    {
        clothes_aid: 11,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "699",
        clothes_image: "na-card-k1.jpg",
        clothes_category: "Summer",
        clothes_is_active: true,
    },
    {
        clothes_aid: 12,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "999",
        clothes_image: "na-card-l1.jpg",
        clothes_category: "Summer",
        clothes_is_active: true,
    },
    {
        clothes_aid: 13,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "298",
        clothes_image: "wc-card-a1.jpg",
        clothes_category: "Winter",
        clothes_is_active: false,
    },
    {
        clothes_aid: 14,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "399",
        clothes_image: "wc-card-b1.jpg",
        clothes_category: "Winter",
        clothes_is_active: true,
    },
    {
        clothes_aid: 14,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "399",
        clothes_image: "wc-card-c1.jpg",
        clothes_category: "Winter",
        clothes_is_active: true,
    },
    {
        clothes_aid: 14,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "399",
        clothes_image: "wc-card-d1.jpg",
        clothes_category: "Winter",
        clothes_is_active: false,
    },
    {
        clothes_aid: 15,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "399",
        clothes_image: "wc-card-e1.jpg",
        clothes_category: "Winter",
        clothes_is_active: true,
    },
    {
        clothes_aid: 16,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "399",
        clothes_image: "wc-card-f1.jpg",
        clothes_category: "Winter",
        clothes_is_active: true,
    },
    {
        clothes_aid: 17,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "399",
        clothes_image: "wc-card-g1.jpg",
        clothes_category: "Winter",
        clothes_is_active: true,
    },
    {
        clothes_aid: 18,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "399",
        clothes_image: "wc-card-h1.jpg",
        clothes_category: "Winter",
        clothes_is_active: true,
    },
    {
        clothes_aid: 19,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "399",
        clothes_image: "wc-card-i1.jpg",
        clothes_category: "Winter",
        clothes_is_active: false,
    },
    {
        clothes_aid: 20,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "399",
        clothes_image: "wc-card-j1.jpg",
        clothes_category: "Winter",
        clothes_is_active: true,
    },
    {
        clothes_aid: 21,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "399",
        clothes_image: "wc-card-k1.jpg",
        clothes_category: "Winter",
        clothes_is_active: true,
    },
    {
        clothes_aid: 22,
        clothes_title: "Lorem ipsum dolor sit amet.",
        clothes_price: "399",
        clothes_image: "wc-card-l1.jpg",
        clothes_category: "Winter",
        clothes_is_active: true,
    },
]