export const newArrivalArray = [
    {
        img1:"na-card-a2.jpg",
        img2:"na-card-a1.jpg",
        title: "1Lorem ipsum dolor sit amet",
        slug: "1lorem-ipsum-dolor-sit-amet",
        price: "149.99",
        thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg", "na-card-b1.jpg", "na-card-b2.jpg"],
        sizes: [23, 24, 25, 26, 27, 29],
        rating: 3,
    },
    {
        img1:"na-card-b2.jpg",
        img2:"na-card-b1.jpg",
        title: "2Lorem ipsum dolor sit amet",
        slug: "2lorem-ipsum-dolor-sit-amet",
        price: "149.99",
        thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
        sizes: [23, 24, 25, 26, 27, 29],
        rating: 5,
    },
    {
        img1:"na-card-c2.jpg",
        img2:"na-card-c1.jpg",
        title: "3Lorem ipsum dolor sit amet",
        slug: "3lorem-ipsum-dolor-sit-amet",
        price: "149.99",
        thumbnails: ["na-card-b1.jpg", "na-card-b2.jpg"],
        sizes: [23, 24, 25, 26, 27, 29],
        rating: 2,
    },
    {
        img1:"na-card-d2.jpg",
        img2:"na-card-d1.jpg",
        title: "4Lorem ipsum dolor sit amet",
        slug: "4lorem-ipsum-dolor-sit-amet",
        price: "149.99",
        thumbnails: ["na-card-c1.jpg", "na-card-c2.jpg"],
        sizes: [23, 24, 25, 26, 27, 29],
        rating: 3,
    },
    {
        img1:"na-card-e2.jpg",
        img2:"na-card-e1.jpg",
        title: "5Lorem ipsum dolor sit amet",
        slug: "5lorem-ipsum-dolor-sit-amet",
        price: "149.99",
        thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
        sizes: [23, 24, 25, 26, 27, 29],
        rating: 1,
    },
    {
        img1:"na-card-f2.jpg",
        img2:"na-card-f1.jpg",
        title: "6Lorem ipsum dolor sit amet",
        slug: "6lorem-ipsum-dolor-sit-amet",
        price: "149.99",
        thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
        sizes: [23, 24, 25, 26, 27, 29],
        rating: 4,
    },
    {
        img1:"na-card-g2.jpg",
        img2:"na-card-g1.jpg",
        title: "7Lorem ipsum dolor sit amet",
        slug: "7lorem-ipsum-dolor-sit-amet",
        price: "149.99",
        thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
        sizes: [23, 24, 25, 26, 27, 29],
        rating: 3,
    },
    {
        img1:"na-card-h2.jpg",
        img2:"na-card-h1.jpg",
        title: "8Lorem ipsum dolor sit amet",
        slug: "8lorem-ipsum-dolor-sit-amet",
        price: "149.99",
        thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
        sizes: [23, 24, 25, 26, 27, 29],
        rating: 5,
    },
    {
        img1:"na-card-i2.jpg",
        img2:"na-card-i1.jpg",
        title: "9Lorem ipsum dolor sit amet",
        slug: "9lorem-ipsum-dolor-sit-amet",
        price: "149.99",
        thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
        sizes: [23, 24, 25, 26, 27, 29],
        rating: 5,
    },
    {
        img1:"na-card-j2.jpg",
        img2:"na-card-j1.jpg",
        title: "10Lorem ipsum dolor sit amet",
        slug: "10lorem-ipsum-dolor-sit-amet",
        price: "149.99",
        thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
        sizes: [23, 24, 25, 26, 27, 29],
        rating: 2,
    },
    {
        img1:"na-card-k2.jpg",
        img2:"na-card-k1.jpg",
        title: "11Lorem ipsum dolor sit amet",
        slug: "11lorem-ipsum-dolor-sit-amet",
        price: "149.99",
        thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
        sizes: [23, 24, 25, 26, 27, 29],
        rating: 1,
    },
    {
        img1:"na-card-l2.jpg",
        img2:"na-card-l1.jpg",
        title: "12Lorem ipsum dolor sit amet",
        slug: "12lorem-ipsum-dolor-sit-amet",
        price: "149.99",
        thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
        sizes: [23, 24, 25, 26, 27, 29],
        rating: 3,
    },

];